### ISSUE TITLE
Is Cerveau closed-source?

### ISSUE THREAD

**Issue by aduh95** [srid/cerveau-issues#12]
Hey,

Thanks for your amazing work. I was wondering, since there is no link to Cerveau source code on the web interface, if it was actually open source. If that's not the case, maybe you could add a note in the footer saying the code source belongs to you (`© 2020 srid` or something like that) or in this repo's README.

FWIW, I was looking for the source code to try to understand the why GitHub connection requires such permissions – the `Act on your behalf` one caught my eye.

**Comment by srid** [comment]
For the possibility of open-sourcing Cerveau, please see https://twitter.com/sridca/status/1302280845902970883

As for the "Act on your behalf" message, that is nothing to worry about--it is just GitHub's terrible UX messaging. For details, see https://twitter.com/sridca/status/1299016929068412929

**Comment by aduh95** [comment]
Oh great, thanks for the info. I can see that there is a link to your GitHub Sponsors profile once I'm logged in, maybe it would be worth to add it to the splash screen for unlogged users as well?

**Comment by srid** [comment]
Good idea. I'll do that.

**Comment by srid** [comment]
The link in the footer points to guide.cerveau.app which has been rewritten.
